/**
 * CS2212 Assignment 4
 * Group: 32
 * @author Avrilyn Li , Sha Liu , Jason Xie , Yunzhuo Zhang 
 * Purpose: this class obtains data generated by the analysis server and convert it into line charts and reports.
 */

package FinalVersion;
import java.util.Vector;
/**
 * Main method
 * @param args
 */
public class Main {
public static void main(String[] args) {
	LoginUI g = LoginUI.getInstance();
	g.make();
	g = null;
}
}
